/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  OperatorFilterer,
  OperatorFiltererInterface,
} from "../../../contracts/operator-filter-registry/OperatorFilterer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "OperatorNotAllowed",
    type: "error",
  },
] as const;

export class OperatorFilterer__factory {
  static readonly abi = _abi;
  static createInterface(): OperatorFiltererInterface {
    return new utils.Interface(_abi) as OperatorFiltererInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OperatorFilterer {
    return new Contract(address, _abi, signerOrProvider) as OperatorFilterer;
  }
}
