/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as badBeaconSol from "./BadBeacon.sol";
export * as uupsLegacySol from "./UUPSLegacy.sol";
export * as uupsUpgradeableMockSol from "./UUPSUpgradeableMock.sol";
export { ClashingImplementation__factory } from "./ClashingImplementation__factory";
