/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorVoteMockSol from "./GovernorVoteMock.sol";
export type { governorVoteMockSol };
export type { GovernorCompMock } from "./GovernorCompMock";
export type { GovernorCompatibilityBravoMock } from "./GovernorCompatibilityBravoMock";
export type { GovernorMock } from "./GovernorMock";
export type { GovernorPreventLateQuorumMock } from "./GovernorPreventLateQuorumMock";
export type { GovernorTimelockCompoundMock } from "./GovernorTimelockCompoundMock";
export type { GovernorTimelockControlMock } from "./GovernorTimelockControlMock";
export type { GovernorWithParamsMock } from "./GovernorWithParamsMock";
