/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721ConsecutiveMockSol from "./ERC721ConsecutiveMock.sol";
export type { erc721ConsecutiveMockSol };
import type * as votesTimestampSol from "./VotesTimestamp.sol";
export type { votesTimestampSol };
export type { ERC1155ReceiverMock } from "./ERC1155ReceiverMock";
export type { ERC20DecimalsMock } from "./ERC20DecimalsMock";
export type { ERC20FlashMintMock } from "./ERC20FlashMintMock";
export type { ERC20MulticallMock } from "./ERC20MulticallMock";
export type { ERC20NoReturnMock } from "./ERC20NoReturnMock";
export type { ERC20PermitNoRevertMock } from "./ERC20PermitNoRevertMock";
export type { ERC20ReturnFalseMock } from "./ERC20ReturnFalseMock";
export type { ERC20ReturnTrueMock } from "./ERC20ReturnTrueMock";
export type { ERC20VotesLegacyMock } from "./ERC20VotesLegacyMock";
export type { ERC4626DecimalsMock } from "./ERC4626DecimalsMock";
export type { ERC721ConsecutiveEnumerableMock } from "./ERC721ConsecutiveEnumerableMock";
export type { ERC721ReceiverMock } from "./ERC721ReceiverMock";
export type { ERC721URIStorageMock } from "./ERC721URIStorageMock";
export type { ERC777Mock } from "./ERC777Mock";
export type { ERC777SenderRecipientMock } from "./ERC777SenderRecipientMock";
