/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc721ConsecutiveMockSol from "./ERC721ConsecutiveMock.sol";
export * as votesTimestampSol from "./VotesTimestamp.sol";
export { ERC1155ReceiverMock__factory } from "./ERC1155ReceiverMock__factory";
export { ERC20DecimalsMock__factory } from "./ERC20DecimalsMock__factory";
export { ERC20FlashMintMock__factory } from "./ERC20FlashMintMock__factory";
export { ERC20MulticallMock__factory } from "./ERC20MulticallMock__factory";
export { ERC20NoReturnMock__factory } from "./ERC20NoReturnMock__factory";
export { ERC20PermitNoRevertMock__factory } from "./ERC20PermitNoRevertMock__factory";
export { ERC20ReturnFalseMock__factory } from "./ERC20ReturnFalseMock__factory";
export { ERC20ReturnTrueMock__factory } from "./ERC20ReturnTrueMock__factory";
export { ERC20VotesLegacyMock__factory } from "./ERC20VotesLegacyMock__factory";
export { ERC4626DecimalsMock__factory } from "./ERC4626DecimalsMock__factory";
export { ERC721ConsecutiveEnumerableMock__factory } from "./ERC721ConsecutiveEnumerableMock__factory";
export { ERC721ReceiverMock__factory } from "./ERC721ReceiverMock__factory";
export { ERC721URIStorageMock__factory } from "./ERC721URIStorageMock__factory";
export { ERC777Mock__factory } from "./ERC777Mock__factory";
export { ERC777SenderRecipientMock__factory } from "./ERC777SenderRecipientMock__factory";
