/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface SampleChildInterface extends utils.Interface {
  functions: {
    "child()": FunctionFragment;
    "father()": FunctionFragment;
    "gramps()": FunctionFragment;
    "initialize(uint256,string,uint256,uint256)": FunctionFragment;
    "initialize()": FunctionFragment;
    "initialize(string,uint256)": FunctionFragment;
    "initialize(string)": FunctionFragment;
    "initialize(uint256)": FunctionFragment;
    "isHuman()": FunctionFragment;
    "mother()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "child"
      | "father"
      | "gramps"
      | "initialize(uint256,string,uint256,uint256)"
      | "initialize()"
      | "initialize(string,uint256)"
      | "initialize(string)"
      | "initialize(uint256)"
      | "isHuman"
      | "mother"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "child", values?: undefined): string;
  encodeFunctionData(functionFragment: "father", values?: undefined): string;
  encodeFunctionData(functionFragment: "gramps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize(uint256,string,uint256,uint256)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize(string,uint256)",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize(string)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "isHuman", values?: undefined): string;
  encodeFunctionData(functionFragment: "mother", values?: undefined): string;

  decodeFunctionResult(functionFragment: "child", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "father", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gramps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialize(uint256,string,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialize()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialize(string,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialize(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialize(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isHuman", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mother", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface SampleChild extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SampleChildInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    child(overrides?: CallOverrides): Promise<[BigNumber]>;

    father(overrides?: CallOverrides): Promise<[BigNumber]>;

    gramps(overrides?: CallOverrides): Promise<[string]>;

    "initialize(uint256,string,uint256,uint256)"(
      _mother: PromiseOrValue<BigNumberish>,
      _gramps: PromiseOrValue<string>,
      _father: PromiseOrValue<BigNumberish>,
      _child: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "initialize()"(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "initialize(string,uint256)"(
      _gramps: PromiseOrValue<string>,
      _father: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "initialize(string)"(
      value: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "initialize(uint256)"(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isHuman(overrides?: CallOverrides): Promise<[boolean]>;

    mother(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  child(overrides?: CallOverrides): Promise<BigNumber>;

  father(overrides?: CallOverrides): Promise<BigNumber>;

  gramps(overrides?: CallOverrides): Promise<string>;

  "initialize(uint256,string,uint256,uint256)"(
    _mother: PromiseOrValue<BigNumberish>,
    _gramps: PromiseOrValue<string>,
    _father: PromiseOrValue<BigNumberish>,
    _child: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "initialize()"(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "initialize(string,uint256)"(
    _gramps: PromiseOrValue<string>,
    _father: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "initialize(string)"(
    value: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "initialize(uint256)"(
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isHuman(overrides?: CallOverrides): Promise<boolean>;

  mother(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    child(overrides?: CallOverrides): Promise<BigNumber>;

    father(overrides?: CallOverrides): Promise<BigNumber>;

    gramps(overrides?: CallOverrides): Promise<string>;

    "initialize(uint256,string,uint256,uint256)"(
      _mother: PromiseOrValue<BigNumberish>,
      _gramps: PromiseOrValue<string>,
      _father: PromiseOrValue<BigNumberish>,
      _child: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize()"(overrides?: CallOverrides): Promise<void>;

    "initialize(string,uint256)"(
      _gramps: PromiseOrValue<string>,
      _father: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(string)"(
      value: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(uint256)"(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    isHuman(overrides?: CallOverrides): Promise<boolean>;

    mother(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;
  };

  estimateGas: {
    child(overrides?: CallOverrides): Promise<BigNumber>;

    father(overrides?: CallOverrides): Promise<BigNumber>;

    gramps(overrides?: CallOverrides): Promise<BigNumber>;

    "initialize(uint256,string,uint256,uint256)"(
      _mother: PromiseOrValue<BigNumberish>,
      _gramps: PromiseOrValue<string>,
      _father: PromiseOrValue<BigNumberish>,
      _child: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "initialize()"(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "initialize(string,uint256)"(
      _gramps: PromiseOrValue<string>,
      _father: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "initialize(string)"(
      value: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "initialize(uint256)"(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isHuman(overrides?: CallOverrides): Promise<BigNumber>;

    mother(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    child(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    father(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gramps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "initialize(uint256,string,uint256,uint256)"(
      _mother: PromiseOrValue<BigNumberish>,
      _gramps: PromiseOrValue<string>,
      _father: PromiseOrValue<BigNumberish>,
      _child: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "initialize()"(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(string,uint256)"(
      _gramps: PromiseOrValue<string>,
      _father: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(string)"(
      value: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(uint256)"(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isHuman(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mother(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
